name: Backup Model-Driven App Solution

on:
  workflow_dispatch:
    inputs:
      solutionName:
        description: "Enter the solution unique name (not display name)"
        required: true
        type: string

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js for PAC CLI
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Power Platform CLI (PAC)
        run: npm install -g pac-cli

      - name: Authenticate with Power Platform (Service Principal)
        run: |
          pac auth create \
            --name backupProfile \
            --url "${{ secrets.SOURCE_ENVIRONMENT_URL }}" \
            --applicationId "${{ secrets.PP_CLIENT_ID }}" \
            --clientSecret "${{ secrets.PP_CLIENT_SECRET }}" \
            --tenant "${{ secrets.PP_TENANT_ID }}"

      - name: Verify available solutions
        run: |
          echo "🔍 Listing available solutions in the environment..."
          pac solution list  || echo "⚠️ Could not list solutions — check authentication."

      - name: Export solution ZIP from Dataverse
        run: |
          echo "📦 Preparing export directory..."
          mkdir -p "${{ github.workspace }}/exports"

          echo "🚀 Exporting solution '${{ github.event.inputs.solutionName }}'..."
          pac solution export \
            --name "${{ github.event.inputs.solutionName }}" \
            --path "${{ github.workspace }}/exports" \
            --managed false \
            --overwrite true || echo "⚠️ PAC export command returned an error."

          echo "📂 Checking exported files..."
          if [ -d "${{ github.workspace }}/exports" ]; then
            ls -R "${{ github.workspace }}/exports"
          else
            echo "❌ Export directory not found. The export likely failed."
            exit 1
          fi

          ZIP_FILE="${{ github.workspace }}/exports/${{ github.event.inputs.solutionName }}.zip"
          if [ ! -f "$ZIP_FILE" ]; then
            echo "❌ Export failed — no ZIP file found for '${{ github.event.inputs.solutionName }}'."
            echo "Please verify the solution unique name and app permissions."
            exit 1
          else
            echo "✅ Export successful: $ZIP_FILE"
          fi

      - name: Unpack solution into source folder
        run: |
          echo "🗂️ Unpacking solution..."
          mkdir -p "${{ github.workspace }}/unpacked-solution"
          pac solution unpack \
            --zipFile "${{ github.workspace }}/exports/${{ github.event.inputs.solutionName }}.zip" \
            --folder "${{ github.workspace }}/unpacked-solution" \
            --allowDelete true \
            --processCanvasApps

          echo "📁 Unpack complete. Folder contents:"
          ls -R "${{ github.workspace }}/unpacked-solution" || echo "⚠️ Nothing unpacked."

      - name: Commit and Push Unpacked Solution
        run: |
          cd "${{ github.workspace }}"
          if [ -d "./unpacked-solution" ] && [ "$(ls -A ./unpacked-solution)" ]; then
            BRANCH_NAME="backup-$(date +'%Y-%m-%d_%H-%M-%S')"
            git checkout -b "$BRANCH_NAME"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add unpacked-solution
            git commit -m "Backup of solution: ${{ github.event.inputs.solutionName }} at $(date)"
            git push origin "$BRANCH_NAME"
            echo "✅ Backup complete and pushed to branch: $BRANCH_NAME"
          else
            echo "❌ ERROR: 'unpacked-solution' folder is missing or empty."
            exit 1
          fi
