name: Backup Model-Driven App Solution

on:
  workflow_dispatch:
    inputs:
      environmentUrl:
        description: 'Power Platform environment URL'
        required: true
        default: 'https://inprovagroupdev.crm4.dynamics.com'
      solutionName:
        description: 'Unique name of the solution to back up'
        required: true
        default: 'TestExport'

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Power Platform CLI
        run: |
          npm install -g pac-cli
          pac --version

      - name: Authenticate with Power Platform
        run: |
          pac auth create \
            --name backupProfile \
            --url "${{ github.event.inputs.environmentUrl }}" \
            --applicationId "${{ secrets.PP_CLIENT_ID }}" \
            --clientSecret "${{ secrets.PP_CLIENT_SECRET }}" \
            --tenant "${{ secrets.PP_TENANT_ID }}"
          echo "Listing all solutions in the environment:"
          pac solution list --publisher

      - name: Clone Solution Source (unpack)
        run: |
          echo "Attempting to clone solution: ${{ github.event.inputs.solutionName }}"
          pac solution clone \
            --name "${{ github.event.inputs.solutionName }}" \
            --path "./unpacked-solution"
          echo "Listing folder contents after clone:"
          ls -la ./unpacked-solution || echo "Folder does not exist. Check solution name and permissions."

      - name: Commit and Push Unpacked Solution
        run: |
          if [ -d "./unpacked-solution" ] && [ "$(ls -A ./unpacked-solution)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add unpacked-solution
            git diff-index --quiet HEAD || git commit -m "Backup of ${{ github.event.inputs.solutionName }}"
            git push
          else
            echo "Folder 'unpacked-solution' does not exist or is empty. Skipping commit."
          fi
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
