name: Backup Model-Driven App Solution

on:
  workflow_dispatch:
    inputs:
      solutionName:
        description: "Enter the solution unique name (not display name)"
        required: true
        type: string

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js for PAC CLI
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Power Platform CLI
        run: npm install -g pac-cli

      - name: Authenticate with Power Platform (Service Principal)
        run: |
          pac auth create \
            --name backupProfile \
            --url "${{ secrets.SOURCE_ENVIRONMENT_URL }}" \
            --applicationId "${{ secrets.PP_CLIENT_ID }}" \
            --clientSecret "${{ secrets.PP_CLIENT_SECRET }}" \
            --tenant "${{ secrets.PP_TENANT_ID }}"

      - name: Verify available solutions
        run: |
          echo "Listing available solutions in the environment..."
          pac solution list 

       - name: Export solution ZIP from Dataverse
        run: |
          echo "Preparing export directory..."
          mkdir -p "${{ github.workspace }}/exports"
      
          echo "Exporting solution ${{ github.event.inputs.solutionName }}..."
          pac solution export \
            --name "${{ github.event.inputs.solutionName }}" \
            --path "${{ github.workspace }}/exports" \
            --managed false \
            --overwrite true
      
          echo "Export complete. Files in exports folder:"
          ls -R "${{ github.workspace }}/exports" || echo "❌ No exported files found!"


      - name: Unpack solution into source folder
        run: |
          echo "Unpacking solution..."
          mkdir -p "${{ github.workspace }}/unpacked-solution"
          pac solution unpack \
            --zipFile "${{ github.workspace }}/exports/${{ github.event.inputs.solutionName }}.zip" \
            --folder "${{ github.workspace }}/unpacked-solution" \
            --allowDelete true \
            --processCanvasApps
          echo "Unpack complete. Folder contents:"
          ls -R "${{ github.workspace }}/unpacked-solution"

      - name: Commit and Push Unpacked Solution
        run: |
          cd "${{ github.workspace }}"
          if [ -d "./unpacked-solution" ] && [ "$(ls -A ./unpacked-solution)" ]; then
            BRANCH_NAME="backup-$(date +'%Y-%m-%d_%H-%M-%S')"
            git checkout -b "$BRANCH_NAME"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add unpacked-solution
            git commit -m "Backup of solution: ${{ github.event.inputs.solutionName }} at $(date)"
            git push origin "$BRANCH_NAME"
            echo "✅ Backup complete and pushed to branch: $BRANCH_NAME"
          else
            echo "❌ ERROR: unpacked-solution folder is missing or empty."
            exit 1
          fi
